<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="1" failures="0" skipped="0" tests="1" time="4.211" timestamp="2025-05-21T21:29:31.014296" hostname="OA1"><testcase classname="" name="tests.acoes.test_integracao_acoes" time="0.000"><error message="collection failure">ImportError while importing test module 'C:\Users\filip\OneDrive\√Årea de Trabalho\autocura\tests\acoes\test_integracao_acoes.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
C:\Python313\Lib\site-packages\_pytest\python.py:617: in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
C:\Python313\Lib\site-packages\_pytest\pathlib.py:565: in import_path
    importlib.import_module(module_name)
C:\Python313\Lib\importlib\__init__.py:88: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
&lt;frozen importlib._bootstrap&gt;:1387: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:1360: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:1331: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:935: in _load_unlocked
    ???
C:\Python313\Lib\site-packages\_pytest\assertion\rewrite.py:178: in exec_module
    exec(co, module.__dict__)
tests\acoes\test_integracao_acoes.py:20: in &lt;module&gt;
    from src.core.acoes_correcao import (
src\core\acoes_correcao.py:9: in &lt;module&gt;
    from ..memoria.gerenciador_memoria import GerenciadorMemoria
E   ModuleNotFoundError: No module named 'src.memoria'</error></testcase></testsuite></testsuites>